### ISSUE TITLE
regen-api successfully exits on swagger enum without associated code being generated

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode-native#1449]
# problem

```yml
name: Thing
type: string
enum:
  - a
  - b
  - c
```

may generate code that refers to a `Thing` model, whilst never generating a `Thing.[ios|java]`
